package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/client/health"
	"github.com/declanshanaghy/bbqberry/client/temperature"
)

// Default app HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new app HTTP client.
func NewHTTPClient(formats strfmt.Registry) *App {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/v1", []string{"http"})
	return New(transport, formats)
}

// New creates a new app client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *App {
	cli := new(App)
	cli.Transport = transport

	cli.Health = health.New(transport, formats)

	cli.Temperature = temperature.New(transport, formats)

	return cli
}

// App is a client for app
type App struct {
	Health *health.Client

	Temperature *temperature.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *App) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Health.SetTransport(transport)

	c.Temperature.SetTransport(transport)

}
