package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/client/hardware"
	"github.com/declanshanaghy/bbqberry/client/health"
	"github.com/declanshanaghy/bbqberry/client/lights"
	"github.com/declanshanaghy/bbqberry/client/monitors"
	"github.com/declanshanaghy/bbqberry/client/system"
	"github.com/declanshanaghy/bbqberry/client/temperatures"
)

// Default bbqberry HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new bbqberry HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Bbqberry {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new bbqberry HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Bbqberry {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new bbqberry client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Bbqberry {
	cli := new(Bbqberry)
	cli.Transport = transport

	cli.Hardware = hardware.New(transport, formats)

	cli.Health = health.New(transport, formats)

	cli.Lights = lights.New(transport, formats)

	cli.Monitors = monitors.New(transport, formats)

	cli.System = system.New(transport, formats)

	cli.Temperatures = temperatures.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Bbqberry is a client for bbqberry
type Bbqberry struct {
	Hardware *hardware.Client

	Health *health.Client

	Lights *lights.Client

	Monitors *monitors.Client

	System *system.Client

	Temperatures *temperatures.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Bbqberry) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Hardware.SetTransport(transport)

	c.Health.SetTransport(transport)

	c.Lights.SetTransport(transport)

	c.Monitors.SetTransport(transport)

	c.System.SetTransport(transport)

	c.Temperatures.SetTransport(transport)

}
