package example

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// HelloReader is a Reader for the Hello structure.
type HelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewHelloDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHelloOK creates a HelloOK with default headers values
func NewHelloOK() *HelloOK {
	return &HelloOK{}
}

/*HelloOK handles this case with default header values.

Sample hello world endpoint
*/
type HelloOK struct {
	Payload *models.Hello
}

func (o *HelloOK) Error() string {
	return fmt.Sprintf("[GET /hello][%d] helloOK  %+v", 200, o.Payload)
}

func (o *HelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Hello)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHelloDefault creates a HelloDefault with default headers values
func NewHelloDefault(code int) *HelloDefault {
	return &HelloDefault{
		_statusCode: code,
	}
}

/*HelloDefault handles this case with default header values.

Unexpected error
*/
type HelloDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the hello default response
func (o *HelloDefault) Code() int {
	return o._statusCode
}

func (o *HelloDefault) Error() string {
	return fmt.Sprintf("[GET /hello][%d] hello default  %+v", o._statusCode, o.Payload)
}

func (o *HelloDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
