package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new monitors API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for monitors API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateMonitor gets monitor settings for the requested probe
*/
func (a *Client) CreateMonitor(params *CreateMonitorParams) (*CreateMonitorOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateMonitorParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createMonitor",
		Method:             "POST",
		PathPattern:        "/monitors",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateMonitorReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateMonitorOK), nil

}

/*
GetMonitors gets monitor settings for the requested probe
*/
func (a *Client) GetMonitors(params *GetMonitorsParams) (*GetMonitorsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMonitorsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getMonitors",
		Method:             "GET",
		PathPattern:        "/monitors",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMonitorsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetMonitorsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
