package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// UpdateMonitorReader is a Reader for the UpdateMonitor structure.
type UpdateMonitorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMonitorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateMonitorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateMonitorDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateMonitorOK creates a UpdateMonitorOK with default headers values
func NewUpdateMonitorOK() *UpdateMonitorOK {
	return &UpdateMonitorOK{}
}

/*UpdateMonitorOK handles this case with default header values.

The monitor was created successfully
*/
type UpdateMonitorOK struct {
}

func (o *UpdateMonitorOK) Error() string {
	return fmt.Sprintf("[PUT /monitors][%d] updateMonitorOK ", 200)
}

func (o *UpdateMonitorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMonitorDefault creates a UpdateMonitorDefault with default headers values
func NewUpdateMonitorDefault(code int) *UpdateMonitorDefault {
	return &UpdateMonitorDefault{
		_statusCode: code,
	}
}

/*UpdateMonitorDefault handles this case with default header values.

Unexpected error
*/
type UpdateMonitorDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update monitor default response
func (o *UpdateMonitorDefault) Code() int {
	return o._statusCode
}

func (o *UpdateMonitorDefault) Error() string {
	return fmt.Sprintf("[PUT /monitors][%d] updateMonitor default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateMonitorDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
