# Start from the latest PolarisHQ skel-app container
FROM hypriot/rpi-alpine-scratch

USER root
EXPOSE 80

COPY /tmp/bin/bbqberry /go/bin/
COPY static /var/www/

CMD ["/go/bin/bbqberry", "--host=0.0.0.0", "--port=80", "--static=/var/www/static"]