swagger: "2.0"
info:
  description: "Rest API definition for BBQ Berry"
  version: "v1"
  title: "BBQ Berry"
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /system/shutdown:
    put:
      operationId: shutdown
      tags:
        - System
      summary: "Shutdown the Operating System"
      responses:
        200:
          description: "Shutdown executed successfully"
          schema:
            $ref: "#/definitions/Shutdown"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /lights/grill:
    get:
      operationId: getGrillLights
      tags:
        - Lights
      summary: "Get the colors currently showing on the grill lights"
      responses:
        200:
          description: "Pixels were read successfully"
          schema:
            type: object
            items:
              $ref: "#/definitions/LightStrip"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    put:
      operationId: updateGrillLights
      tags:
        - Lights
      summary: "Enable a light show on the grill lights"
      parameters:
        - name: name
          description: The light show to enable
          in: query
          required: true
          type: string
          enum: ["Simple Shifter", "Rainbow", "Temperature"]
        - name: period
          description: The time period between updates in microseconds
          in: query
          required: true
          type: integer
          minimum: 1
          default: 500000
      responses:
        200:
          description: "The lights were updated successfully"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /monitors:
    put:
      operationId: updateMonitor
      tags:
        - Monitors
      summary: "Update monitor settings for the requested probe"
      parameters:
        - name: probe
          type: integer
          format: int32
          minimum: 0
          maximum: 3
          in: query
          required: true
        - name: scale
          type: string
          description: The temperature scale
          enum:
            - celsius
          in: query
          required: true
        - name: min
          type: integer
          format: int32
          description: The minimum temperature, below which an alert will be generated
          in: query
          required: true
        - name: max
          type: integer
          format: int32
          description: The maximium temperature, above which an alert will be generated
          in: query
          required: true
      responses:
        200:
          description: "The monitor was created successfully"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /alerts:
    put:
      operationId: updateAlert
      tags:
        - Alerts
      summary: "Clear alert warning for a probe"
      parameters:
        - name: probe
          in: query
          required: true
          type: integer
          minimum: 0
          maximum: 3
      responses:
        200:
          description: "The monitor was created successfully"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /temperatures:
    get:
      operationId: getTemperatures
      tags:
        - Temperatures
      summary: "Get the current temperature reading from the requested probe(s)"
      parameters:
        - name: probe
          in: query
          description: The termerature probe to read from (or all probes if omitted)
          required: false
          type: integer
          format: int32
          minimum: 0
          maximum: 3
      responses:
        200:
          description: "Temperature was read successfully"
          schema:
            type: array
            items:
              $ref: "#/definitions/TemperatureReading"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /hardware:
    get:
      operationId: getHardware
      tags:
        - Hardware
      summary: "Get current configuration settings"
      responses:
        200:
          description: "The config was retrieved successfully"
          schema:
            $ref: "#/definitions/HardwareConfig"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /health:
    get:
      operationId: health
      tags:
        - Health
      summary: "UNVERSIONED Health check endpoint. Required for all services"
      description: |
        Performs detailed internal checks and reports back whether or not the service is operating properly
        https://confluence.splunk.com/display/PROD/Common+Microservice+Endpoints+and+Version+Management
      responses:
        200:
          description: "Service is operating normally"
          schema:
            $ref: "#/definitions/Health"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

definitions:
  TemperatureLimits:
    type: object
    required:
      - probeType
      - minWarnCelsius
      - maxWarnCelsius
      - minAbsCelsius
      - maxAbsCelsius
    properties:
      probeType:
        type: string
        description: Ambient probes measure air temperature. Cooking probes measure food temperature
      minWarnCelsius:
        type: integer
        format: int32
      maxWarnCelsius:
        type: integer
        format: int32
      minAbsCelsius:
        type: integer
        format: int32
      maxAbsCelsius:
        type: integer
        format: int32
  TemperatureProbe:
    type: object
    required:
      - label
      - enabled
      - limits
    properties:
      label:
        type: string
      enabled:
        type: boolean
      limits:
        $ref: "#/definitions/TemperatureLimits"
  HardwareConfig:
    type: object
    required:
      - numLedPixels
      - vcc
      - analogMax
      - probes
    properties:
      numLedPixels:
        type: integer
        format: int32
        minimum: 0
        default: 0
      vcc:
        type: number
        format: float
        default: 3.3
      analogMax:
        type: integer
        format: int32
        minimum: 0
        default: 1024
      analogVoltsPerUnit:
        description: "The amount the voltage will increase to reflect a unit increase in analog reading"
        type: number
        format: float
        minimum: 0.0
        default: 1000.0
      probes:
        type: array
        items:
          $ref: "#/definitions/TemperatureProbe"
  Shutdown:
    type: object
    required:
      - ShutdownTime
      - Message
    properties:
      ShutdownTime:
        type: string
      Message:
        type: string
  LightStrip:
    type: object
    required:
      - name
      - pixels
    properties:
      name:
        type: string
        description: Name of the light strip
      pixels:
        type: array
        items:
          $ref: "#/definitions/Color"
  Color:
    type: object
    required:
      - hex
    properties:
      hex:
        type: string
        description: Color in hex representation
  TemperatureReading:
    type: object
    required:
      - analog
      - voltage
      - kelvin
      - celsius
      - fahrenheit
      - probe
      - updated
      - warning_ackd
    properties:
      kelvin:
        type: number
        format: int32
        description: Temperature reading in degrees Kelvin
      celsius:
        type: number
        format: int32
        description: Temperature reading in degrees Celsius
      fahrenheit:
        type: number
        format: int32
        description: Temperature reading in degrees Fahrenheit
      updated:
        type: string
        format: date-time
        description: The date and time of the reading
      analog:
        type: integer
        format: int32
        minimum: 0
        maximum: 1023
      voltage:
        type: number
        format: float
        minimum: 0
        maximum: 3.3
      warning:
        type: string
      warning_ackd:
        type: boolean
        default: false
      probe:
        type: integer
        format: int32
        minimum: 0
        maximum: 3
  Error:
    type: object
    required:
      - code
    properties:
      code:
        type: integer
        format: int32
        description: |
          Internal error code. In generic error cases this may be a HTTP status code.
          Therefore internal error codes should not conflict with HTTP status codes.
      message:
        type: string
        description: A brief description of the error
      fields:
        type: string
        description: Optional list of field names which caused the error
  ServiceInfo:
    type: object
    required:
      - name
      - version
    properties:
      name:
        type: string
        description: Service name
      version:
        type: string
        description: Service API version
  Health:
    type: object
    required:
      - healthy
      - service_info
    properties:
      healthy:
        type: boolean
        description: Flag indicating whether or not ALL internal checks passed
      error:
        $ref: "#/definitions/Error"
      service_info:
        $ref: "#/definitions/ServiceInfo"