package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHardwareConfigParams creates a new GetHardwareConfigParams object
// with the default values initialized.
func NewGetHardwareConfigParams() *GetHardwareConfigParams {

	return &GetHardwareConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHardwareConfigParamsWithTimeout creates a new GetHardwareConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHardwareConfigParamsWithTimeout(timeout time.Duration) *GetHardwareConfigParams {

	return &GetHardwareConfigParams{

		timeout: timeout,
	}
}

// NewGetHardwareConfigParamsWithContext creates a new GetHardwareConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHardwareConfigParamsWithContext(ctx context.Context) *GetHardwareConfigParams {

	return &GetHardwareConfigParams{

		Context: ctx,
	}
}

/*GetHardwareConfigParams contains all the parameters to send to the API endpoint
for the get hardware config operation typically these are written to a http.Request
*/
type GetHardwareConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hardware config params
func (o *GetHardwareConfigParams) WithTimeout(timeout time.Duration) *GetHardwareConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hardware config params
func (o *GetHardwareConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hardware config params
func (o *GetHardwareConfigParams) WithContext(ctx context.Context) *GetHardwareConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hardware config params
func (o *GetHardwareConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetHardwareConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
