package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// GetHardwareConfigReader is a Reader for the GetHardwareConfig structure.
type GetHardwareConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHardwareConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHardwareConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetHardwareConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetHardwareConfigOK creates a GetHardwareConfigOK with default headers values
func NewGetHardwareConfigOK() *GetHardwareConfigOK {
	return &GetHardwareConfigOK{}
}

/*GetHardwareConfigOK handles this case with default header values.

The config was retrieved successfully
*/
type GetHardwareConfigOK struct {
	Payload *models.HardwareConfig
}

func (o *GetHardwareConfigOK) Error() string {
	return fmt.Sprintf("[GET /hardware/config][%d] getHardwareConfigOK  %+v", 200, o.Payload)
}

func (o *GetHardwareConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HardwareConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHardwareConfigDefault creates a GetHardwareConfigDefault with default headers values
func NewGetHardwareConfigDefault(code int) *GetHardwareConfigDefault {
	return &GetHardwareConfigDefault{
		_statusCode: code,
	}
}

/*GetHardwareConfigDefault handles this case with default header values.

Unexpected error
*/
type GetHardwareConfigDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get hardware config default response
func (o *GetHardwareConfigDefault) Code() int {
	return o._statusCode
}

func (o *GetHardwareConfigDefault) Error() string {
	return fmt.Sprintf("[GET /hardware/config][%d] getHardwareConfig default  %+v", o._statusCode, o.Payload)
}

func (o *GetHardwareConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
