package temperatures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTemperaturesParams creates a new GetTemperaturesParams object
// with the default values initialized.
func NewGetTemperaturesParams() *GetTemperaturesParams {
	var ()
	return &GetTemperaturesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTemperaturesParamsWithTimeout creates a new GetTemperaturesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTemperaturesParamsWithTimeout(timeout time.Duration) *GetTemperaturesParams {
	var ()
	return &GetTemperaturesParams{

		timeout: timeout,
	}
}

// NewGetTemperaturesParamsWithContext creates a new GetTemperaturesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTemperaturesParamsWithContext(ctx context.Context) *GetTemperaturesParams {
	var ()
	return &GetTemperaturesParams{

		Context: ctx,
	}
}

/*GetTemperaturesParams contains all the parameters to send to the API endpoint
for the get temperatures operation typically these are written to a http.Request
*/
type GetTemperaturesParams struct {

	/*Probe
	  The termerature probe to read from (or all probes if omitted)

	*/
	Probe *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get temperatures params
func (o *GetTemperaturesParams) WithTimeout(timeout time.Duration) *GetTemperaturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get temperatures params
func (o *GetTemperaturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get temperatures params
func (o *GetTemperaturesParams) WithContext(ctx context.Context) *GetTemperaturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get temperatures params
func (o *GetTemperaturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithProbe adds the probe to the get temperatures params
func (o *GetTemperaturesParams) WithProbe(probe *int32) *GetTemperaturesParams {
	o.SetProbe(probe)
	return o
}

// SetProbe adds the probe to the get temperatures params
func (o *GetTemperaturesParams) SetProbe(probe *int32) {
	o.Probe = probe
}

// WriteToRequest writes these params to a swagger request
func (o *GetTemperaturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Probe != nil {

		// query param probe
		var qrProbe int32
		if o.Probe != nil {
			qrProbe = *o.Probe
		}
		qProbe := swag.FormatInt32(qrProbe)
		if qProbe != "" {
			if err := r.SetQueryParam("probe", qProbe); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
