package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/declanshanaghy/bbqberry/models"
)

// EnableShifterCreatedCode is the HTTP code returned for type EnableShifterCreated
const EnableShifterCreatedCode int = 201

/*EnableShifterCreated The monitor was created successfully

swagger:response enableShifterCreated
*/
type EnableShifterCreated struct {
}

// NewEnableShifterCreated creates EnableShifterCreated with default headers values
func NewEnableShifterCreated() *EnableShifterCreated {
	return &EnableShifterCreated{}
}

// WriteResponse to the client
func (o *EnableShifterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

/*EnableShifterDefault Unexpected error

swagger:response enableShifterDefault
*/
type EnableShifterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewEnableShifterDefault creates EnableShifterDefault with default headers values
func NewEnableShifterDefault(code int) *EnableShifterDefault {
	if code <= 0 {
		code = 500
	}

	return &EnableShifterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the enable shifter default response
func (o *EnableShifterDefault) WithStatusCode(code int) *EnableShifterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the enable shifter default response
func (o *EnableShifterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the enable shifter default response
func (o *EnableShifterDefault) WithPayload(payload *models.Error) *EnableShifterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enable shifter default response
func (o *EnableShifterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnableShifterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
