package temperature

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new temperature API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for temperature API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTemperature gets the current temperature reading from the given probe
*/
func (a *Client) GetTemperature(params *GetTemperatureParams) (*GetTemperatureOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTemperatureParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTemperature",
		Method:             "GET",
		PathPattern:        "/sensors/temperature/{probe}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTemperatureReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTemperatureOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
