package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// EnableShifterReader is a Reader for the EnableShifter structure.
type EnableShifterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableShifterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewEnableShifterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEnableShifterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEnableShifterCreated creates a EnableShifterCreated with default headers values
func NewEnableShifterCreated() *EnableShifterCreated {
	return &EnableShifterCreated{}
}

/*EnableShifterCreated handles this case with default header values.

The monitor was created successfully
*/
type EnableShifterCreated struct {
}

func (o *EnableShifterCreated) Error() string {
	return fmt.Sprintf("[PUT /lights/shifter][%d] enableShifterCreated ", 201)
}

func (o *EnableShifterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEnableShifterDefault creates a EnableShifterDefault with default headers values
func NewEnableShifterDefault(code int) *EnableShifterDefault {
	return &EnableShifterDefault{
		_statusCode: code,
	}
}

/*EnableShifterDefault handles this case with default header values.

Unexpected error
*/
type EnableShifterDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the enable shifter default response
func (o *EnableShifterDefault) Code() int {
	return o._statusCode
}

func (o *EnableShifterDefault) Error() string {
	return fmt.Sprintf("[PUT /lights/shifter][%d] enableShifter default  %+v", o._statusCode, o.Payload)
}

func (o *EnableShifterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
