package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// GetGrillLightsReader is a Reader for the GetGrillLights structure.
type GetGrillLightsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGrillLightsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGrillLightsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetGrillLightsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetGrillLightsOK creates a GetGrillLightsOK with default headers values
func NewGetGrillLightsOK() *GetGrillLightsOK {
	return &GetGrillLightsOK{}
}

/*GetGrillLightsOK handles this case with default header values.

Pixels were read successfully
*/
type GetGrillLightsOK struct {
	Payload GetGrillLightsOKBody
}

func (o *GetGrillLightsOK) Error() string {
	return fmt.Sprintf("[GET /lights/grill][%d] getGrillLightsOK  %+v", 200, o.Payload)
}

func (o *GetGrillLightsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGrillLightsDefault creates a GetGrillLightsDefault with default headers values
func NewGetGrillLightsDefault(code int) *GetGrillLightsDefault {
	return &GetGrillLightsDefault{
		_statusCode: code,
	}
}

/*GetGrillLightsDefault handles this case with default header values.

Unexpected error
*/
type GetGrillLightsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get grill lights default response
func (o *GetGrillLightsDefault) Code() int {
	return o._statusCode
}

func (o *GetGrillLightsDefault) Error() string {
	return fmt.Sprintf("[GET /lights/grill][%d] getGrillLights default  %+v", o._statusCode, o.Payload)
}

func (o *GetGrillLightsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetGrillLightsOKBody get grill lights o k body
swagger:model GetGrillLightsOKBody
*/
type GetGrillLightsOKBody []*models.LightStrip
