package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGrillLightsParams creates a new GetGrillLightsParams object
// with the default values initialized.
func NewGetGrillLightsParams() *GetGrillLightsParams {

	return &GetGrillLightsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGrillLightsParamsWithTimeout creates a new GetGrillLightsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGrillLightsParamsWithTimeout(timeout time.Duration) *GetGrillLightsParams {

	return &GetGrillLightsParams{

		timeout: timeout,
	}
}

// NewGetGrillLightsParamsWithContext creates a new GetGrillLightsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGrillLightsParamsWithContext(ctx context.Context) *GetGrillLightsParams {

	return &GetGrillLightsParams{

		Context: ctx,
	}
}

// NewGetGrillLightsParamsWithHTTPClient creates a new GetGrillLightsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGrillLightsParamsWithHTTPClient(client *http.Client) *GetGrillLightsParams {

	return &GetGrillLightsParams{
		HTTPClient: client,
	}
}

/*GetGrillLightsParams contains all the parameters to send to the API endpoint
for the get grill lights operation typically these are written to a http.Request
*/
type GetGrillLightsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get grill lights params
func (o *GetGrillLightsParams) WithTimeout(timeout time.Duration) *GetGrillLightsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get grill lights params
func (o *GetGrillLightsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get grill lights params
func (o *GetGrillLightsParams) WithContext(ctx context.Context) *GetGrillLightsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get grill lights params
func (o *GetGrillLightsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get grill lights params
func (o *GetGrillLightsParams) WithHTTPClient(client *http.Client) *GetGrillLightsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get grill lights params
func (o *GetGrillLightsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGrillLightsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
