package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new lights API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for lights API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetGrillLights gets the colors currently showing on the grill lights
*/
func (a *Client) GetGrillLights(params *GetGrillLightsParams) (*GetGrillLightsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGrillLightsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGrillLights",
		Method:             "GET",
		PathPattern:        "/lights/grill",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGrillLightsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetGrillLightsOK), nil

}

/*
UpdateGrillLights enables a light show on the grill lights
*/
func (a *Client) UpdateGrillLights(params *UpdateGrillLightsParams) (*UpdateGrillLightsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateGrillLightsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateGrillLights",
		Method:             "PUT",
		PathPattern:        "/lights/grill",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateGrillLightsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UpdateGrillLightsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
