package lights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// UpdateGrillLightsReader is a Reader for the UpdateGrillLights structure.
type UpdateGrillLightsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateGrillLightsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateGrillLightsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateGrillLightsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateGrillLightsOK creates a UpdateGrillLightsOK with default headers values
func NewUpdateGrillLightsOK() *UpdateGrillLightsOK {
	return &UpdateGrillLightsOK{}
}

/*UpdateGrillLightsOK handles this case with default header values.

The lights were updated successfully
*/
type UpdateGrillLightsOK struct {
}

func (o *UpdateGrillLightsOK) Error() string {
	return fmt.Sprintf("[PUT /lights/grill][%d] updateGrillLightsOK ", 200)
}

func (o *UpdateGrillLightsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateGrillLightsDefault creates a UpdateGrillLightsDefault with default headers values
func NewUpdateGrillLightsDefault(code int) *UpdateGrillLightsDefault {
	return &UpdateGrillLightsDefault{
		_statusCode: code,
	}
}

/*UpdateGrillLightsDefault handles this case with default header values.

Unexpected error
*/
type UpdateGrillLightsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update grill lights default response
func (o *UpdateGrillLightsDefault) Code() int {
	return o._statusCode
}

func (o *UpdateGrillLightsDefault) Error() string {
	return fmt.Sprintf("[PUT /lights/grill][%d] updateGrillLights default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateGrillLightsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
