package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/declanshanaghy/bbqberry/models"
)

// UpdateAlertOKCode is the HTTP code returned for type UpdateAlertOK
const UpdateAlertOKCode int = 200

/*UpdateAlertOK The monitor was created successfully

swagger:response updateAlertOK
*/
type UpdateAlertOK struct {
}

// NewUpdateAlertOK creates UpdateAlertOK with default headers values
func NewUpdateAlertOK() *UpdateAlertOK {
	return &UpdateAlertOK{}
}

// WriteResponse to the client
func (o *UpdateAlertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*UpdateAlertDefault Unexpected error

swagger:response updateAlertDefault
*/
type UpdateAlertDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateAlertDefault creates UpdateAlertDefault with default headers values
func NewUpdateAlertDefault(code int) *UpdateAlertDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateAlertDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update alert default response
func (o *UpdateAlertDefault) WithStatusCode(code int) *UpdateAlertDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update alert default response
func (o *UpdateAlertDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update alert default response
func (o *UpdateAlertDefault) WithPayload(payload *models.Error) *UpdateAlertDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update alert default response
func (o *UpdateAlertDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateAlertDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
