package temperature

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/declanshanaghy/bbqberry/models"
)

/*GetProbeReadingsOK Temperature was read successfully

swagger:response getProbeReadingsOK
*/
type GetProbeReadingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TemperatureReading `json:"body,omitempty"`
}

// NewGetProbeReadingsOK creates GetProbeReadingsOK with default headers values
func NewGetProbeReadingsOK() *GetProbeReadingsOK {
	return &GetProbeReadingsOK{}
}

// WithPayload adds the payload to the get probe readings o k response
func (o *GetProbeReadingsOK) WithPayload(payload *models.TemperatureReading) *GetProbeReadingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get probe readings o k response
func (o *GetProbeReadingsOK) SetPayload(payload *models.TemperatureReading) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProbeReadingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetProbeReadingsDefault Unexpected error

swagger:response getProbeReadingsDefault
*/
type GetProbeReadingsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetProbeReadingsDefault creates GetProbeReadingsDefault with default headers values
func NewGetProbeReadingsDefault(code int) *GetProbeReadingsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetProbeReadingsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get probe readings default response
func (o *GetProbeReadingsDefault) WithStatusCode(code int) *GetProbeReadingsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get probe readings default response
func (o *GetProbeReadingsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get probe readings default response
func (o *GetProbeReadingsDefault) WithPayload(payload *models.Error) *GetProbeReadingsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get probe readings default response
func (o *GetProbeReadingsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProbeReadingsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
