package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHardwareConfigHandlerFunc turns a function with the right signature into a get hardware config handler
type GetHardwareConfigHandlerFunc func(GetHardwareConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHardwareConfigHandlerFunc) Handle(params GetHardwareConfigParams) middleware.Responder {
	return fn(params)
}

// GetHardwareConfigHandler interface for that can handle valid get hardware config params
type GetHardwareConfigHandler interface {
	Handle(GetHardwareConfigParams) middleware.Responder
}

// NewGetHardwareConfig creates a new http.Handler for the get hardware config operation
func NewGetHardwareConfig(ctx *middleware.Context, handler GetHardwareConfigHandler) *GetHardwareConfig {
	return &GetHardwareConfig{Context: ctx, Handler: handler}
}

/*GetHardwareConfig swagger:route GET /hardware/config Config getHardwareConfig

Get current configuration settings

*/
type GetHardwareConfig struct {
	Context *middleware.Context
	Handler GetHardwareConfigHandler
}

func (o *GetHardwareConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetHardwareConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
