package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// UpdateMonitorURL generates an URL for the update monitor operation
type UpdateMonitorURL struct {
	Max   int32
	Min   int32
	Probe int32
	Scale string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateMonitorURL) WithBasePath(bp string) *UpdateMonitorURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateMonitorURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdateMonitorURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/monitors"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	max := swag.FormatInt32(o.Max)
	if max != "" {
		qs.Set("max", max)
	}

	min := swag.FormatInt32(o.Min)
	if min != "" {
		qs.Set("min", min)
	}

	probe := swag.FormatInt32(o.Probe)
	if probe != "" {
		qs.Set("probe", probe)
	}

	scale := o.Scale
	if scale != "" {
		qs.Set("scale", scale)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdateMonitorURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdateMonitorURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdateMonitorURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdateMonitorURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdateMonitorURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdateMonitorURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
