package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateMonitorHandlerFunc turns a function with the right signature into a update monitor handler
type UpdateMonitorHandlerFunc func(UpdateMonitorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMonitorHandlerFunc) Handle(params UpdateMonitorParams) middleware.Responder {
	return fn(params)
}

// UpdateMonitorHandler interface for that can handle valid update monitor params
type UpdateMonitorHandler interface {
	Handle(UpdateMonitorParams) middleware.Responder
}

// NewUpdateMonitor creates a new http.Handler for the update monitor operation
func NewUpdateMonitor(ctx *middleware.Context, handler UpdateMonitorHandler) *UpdateMonitor {
	return &UpdateMonitor{Context: ctx, Handler: handler}
}

/*UpdateMonitor swagger:route PUT /monitors Monitors updateMonitor

Update monitor settings for the requested probe

*/
type UpdateMonitor struct {
	Context *middleware.Context
	Handler UpdateMonitorHandler
}

func (o *UpdateMonitor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateMonitorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
