package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/declanshanaghy/bbqberry/models"
)

// UpdateAlertReader is a Reader for the UpdateAlert structure.
type UpdateAlertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAlertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateAlertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateAlertDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAlertOK creates a UpdateAlertOK with default headers values
func NewUpdateAlertOK() *UpdateAlertOK {
	return &UpdateAlertOK{}
}

/*UpdateAlertOK handles this case with default header values.

The monitor was created successfully
*/
type UpdateAlertOK struct {
}

func (o *UpdateAlertOK) Error() string {
	return fmt.Sprintf("[PUT /alerts][%d] updateAlertOK ", 200)
}

func (o *UpdateAlertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateAlertDefault creates a UpdateAlertDefault with default headers values
func NewUpdateAlertDefault(code int) *UpdateAlertDefault {
	return &UpdateAlertDefault{
		_statusCode: code,
	}
}

/*UpdateAlertDefault handles this case with default header values.

Unexpected error
*/
type UpdateAlertDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update alert default response
func (o *UpdateAlertDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAlertDefault) Error() string {
	return fmt.Sprintf("[PUT /alerts][%d] updateAlert default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAlertDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
