package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Error error
// swagger:model Error
type Error struct {

	// Internal error code. In generic error cases this may be a HTTP status code.
	// Therefore internal error codes should not conflict with HTTP status codes.
	//
	// Required: true
	Code *int32 `json:"code"`

	// Optional list of field names which caused the error
	Fields string `json:"fields,omitempty"`

	// A brief description of the error
	Message string `json:"message,omitempty"`
}

// Validate validates this error
func (m *Error) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Error) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}
