package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Shutdown shutdown
// swagger:model Shutdown
type Shutdown struct {

	// message
	// Required: true
	Message *string `json:"Message"`

	// shutdown time
	// Required: true
	ShutdownTime *string `json:"ShutdownTime"`
}

// Validate validates this shutdown
func (m *Shutdown) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateShutdownTime(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Shutdown) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("Message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *Shutdown) validateShutdownTime(formats strfmt.Registry) error {

	if err := validate.Required("ShutdownTime", "body", m.ShutdownTime); err != nil {
		return err
	}

	return nil
}
