package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TemperatureSetting temperature setting
// swagger:model TemperatureSetting
type TemperatureSetting struct {

	// label
	// Required: true
	Label *string `json:"label"`

	// temp limits
	// Required: true
	TempLimits *TemperatureLimits `json:"tempLimits"`
}

// Validate validates this temperature setting
func (m *TemperatureSetting) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTempLimits(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemperatureSetting) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

func (m *TemperatureSetting) validateTempLimits(formats strfmt.Registry) error {

	if err := validate.Required("tempLimits", "body", m.TempLimits); err != nil {
		return err
	}

	if m.TempLimits != nil {

		if err := m.TempLimits.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tempLimits")
			}
			return err
		}
	}

	return nil
}
